### ISSUE TITLE
npm package page is missing repository link

### ISSUE THREAD

**Issue by feross** [seangenabe/browserify-breakdown#4]
Can you add a repository field so it shows up? https://www.npmjs.com/package/browserify-breakdown

I usually don't trust packages that don't have a repo field, since it's too difficult to find the code. ;)

Great library, cheers!

**Comment by seangenabe** [comment]
Sorry about that. Must be one of those packages that I didn't `npm init` or plan to publicize initially.

Fixed in https://github.com/seangenabe/browserify-breakdown/commit/f8938b88173c07828932afd5b43642553b9e183f

**Comment by seangenabe** [comment]
Published in 1.0.4.

**Comment by feross** [comment]
Thanks!
