### ISSUE TITLE
Mac support: Use unix line endings

### ISSUE THREAD

**Issue by feross** [seangenabe/browserify-breakdown#5]
```bash
$ npm install -g browserify-breakdown
$ browserify-breakdown
env: node\r: No such file or directory
```

If you convert the line endings to unix style, then this will start working for users on non-Windows systems, I believe. If you google for the error message, you can see how others resolved it. For example: https://github.com/nwjs-community/nw-builder/issues/75

**Comment by seangenabe** [comment]
Apparently I do have .gitattributes set up properly but the binary still had crlf. I published 1.0.4 to npm with lf line endings.
